# Série 1
Ce document contient les différents exercices à réaliser. Veuillez compléter et rendre ces exercices pour la semaine prochaine.

Pour chaque exercice:
* implémentez ce qui est demandé
* commentez votre code
* expliquez **en français** ce que vous avez codé dans la cellule correspondante

Dans vos explications à chacun des exercices, indiquez un pourcentage subjectif d'investissement de chaque membre du groupe. **Des interrogations aléatoires en classe pourront être réalisées pour vérifier votre contribution/compréhension.**

## Exercice 1
Le PGCD (plus grand commun diviseur) est le plus grand nombre entier qui divise simultanément deux autres nombres entiers.

Implémentez l'algorithme d'Euclide permettant de calculer le PGCD de deux nombres entiers. Vous trouverez plus d'informations concernant l'algorithme d'Euclide en cliquant sur ce [lien](https://en.wikipedia.org/wiki/Greatest_common_divisor#Euclid's_algorithm).

In [7]:
def gcd(n: int, m: int):
    result = 0
    # A COMPLETER
    while m != 0:
        n, m = m, n%m
        #          ^-- modulo operator!
        result = n
    return result

In [8]:
assert gcd(9,6) == 3
assert gcd(6, 9) == 3
assert gcd(24,32) == 8
assert gcd(18,18) == 18
assert not gcd(10,15) == 10
assert not gcd(12,9) == 4
assert not gcd(14,14) == 34

### Explications

On utilise la variante "Euclidean algorithm", pour calculer le plus grand diviseur commun entre deux nombres. On va utiliser le reste de la division euclidienne pour trouver le PGCD. On va répéter l'opération jusqu'à ce que le reste soit égal à 0. Le dernier diviseur est le PGCD.

#### Algorithme : gcd(n, m)
1. Tant que le deuxième nombre (`m`) n'est pas égal à 0 :
   - On remplace `n` par `m` et `m` par `n % m`.
2. Quand `m` est égal à 0, `n` contient le PGCD des deux nombres de départ.

Autrement dit, on continue de remplacer `n` et `m` jusqu'à ce que le reste (`m`) devienne 0. Le dernier `n` est alors le PGCD.


#### Exemple :
gcd(48,18) = 6 car :
- 48 % 18 = 12
- 18 % 12 = 6
- 12 % 6 = 0
- donc 6 est le PGCD de 48 et 18

## Exercice 2
Implémentez une manière de calculer $x^n$ en utilisant la méthode de dichotomie.

In [13]:
def powdi(x: int, n: int) -> int:
    if n == 0:
        return 1
    if n == 1:
        return x
    if n % 2 == 0:
        return powdi(x, n//2) * powdi(x, n//2)
        
    return x * powdi(x, n//2) * powdi(x, n//2)

In [14]:
assert powdi(2,3) == 8
assert powdi(4,2) == 16
assert powdi(2,2) == 4
assert powdi(4,0) == 1
assert powdi(2,1) == 2
assert not powdi(5,2) == 10
assert not powdi(3,7) == 10
assert not powdi(3,3) == 10

### Explications

Cette méthode pour calculer la $n$-ième puissance de $x$ est de complexité sous-linéaire (sublinear).
Contrairement à l'approche naïve qui consiste à multiplier $x$ par lui-même $n$ fois, cette méthode tire parti des lois des exposants (exposant laws). L'idée est de diviser le problème en sous-problèmes plus petits pour optimiser le calcul de la fonction, surtout lorsque `n` devient grand (diviser pour mieux régner).
Plus précisément, elle utilise le fait que $x^{2k} = (x^k)^2 = x^k * x^k$.

Cette méthode est donc beaucoup plus rapide que la méthode naïve de multiplication répétée, en particulier pour des grands `n`. À chaque étape, on divise `n` par `2`, ce qui réduit la complexité de l'algorithme.


Quelques mots maintenant sur l'implémentation : les deux premières instructions "if" traitent des cas de base, à savoir $x^0 = 1$ et $x^1 = x$.
Une fois que nous avons déterminé que nous ne sommes pas dans l'un de ces cas de base, nous appliquons le schéma ci-dessus.

Notez que nous n'utilisons pas l'opérateur de division standard `/`, mais l'opérateur de division entière `//` ([docs](https://docs.python.org/3/reference/expressions.html#binary-arithmetic-operations)).
Le résultat d'une division entière est celui d'une division régulière avec la fonction `floor` appliquée à son résultat.
En d'autres termes, nous arrondissons toujours vers le bas, jamais vers le haut.
Cela ne pose pas de problème lorsque l'on traite des exposants pairs.
Cependant, il faut en tenir compte lorsque l'on traite des exposants impairs, car sinon nous manquerions une multiplication par `x`.
C'est ce que vérifie la dernière instruction "if", et cela explique pourquoi nous multiplions également par `x` lorsqu'il s'agit de nombres impairs.

Notez que ce schéma ne fonctionne de cette manière que si nous traitons des exposants entiers.
Cette exigence est reflétée dans la signature de la fonction.


#### Algorithme :

- **Cas `n = 0`** :  
  - On retourne `1`, car tout nombre élevé à la puissance `0` est égal à `1`.

- **Cas `n = 1`** :  
  - On retourne `x`, car tout nombre élevé à la puissance `1` est égal à lui-même (`x`).

- **Cas `n` est pair** :  
  - On divise `n` par `2` et on calcule `x^(n/2)`, puis on retourne le carré de ce résultat :  
    `x^(n/2) * x^(n/2)`.
  - Cette approche permet de réduire le nombre d'opérations en réutilisant le résultat intermédiaire.
  - **Exemple** : `x^8 = (x^4) * (x^4)`

- **Cas `n` est impair** :  
  - On divise `n` par `2`, on calcule `x^(n/2)`, puis on retourne le carré de ce résultat multiplié par `x` : 
    `x^(n/2) * x^(n/2) * x`.
  - Cela suit la même logique que dans le cas pair, mais on ajoute `x` à la fin pour compenser le fait que `n` est impair.
  - **Exemple** : `x^9 = (x^4) * (x^4) * x`

## Exercice 3
La suite de Fibonacci est une suite de nombres entiers dans laquelle chaque nombre $f_{n+2}$ correspond à la somme des deux nombres qui le précèdent, $f_{n+1}+f_{n}$.

Implémentez l'algorithme de Fibonacci en utilisant la multiplication matricielle.

In [48]:
import numpy as np
import numpy.typing as np_typing

type TMatrix = np_typing.NDArray[np.int32] | np_typing.NDArray[np.float64]


def powdi(x: TMatrix, n: int) -> TMatrix:
    if n == 0:
        return np.identity(2)
    if n == 1:
        return x
    if n % 2 == 0:
        return powdi(x, n // 2) @ powdi(x, n // 2)

    return x @ powdi(x, n // 2) @ powdi(x, n // 2)


def fibo(n: int):
    f0f1 = np.array([[0], [1]])

    # base matrix used to calculate fibonacci numbers
    fibonacci_matrix = np.array([[0, 1], [1, 1]])
    # calculate the power of the base matrix
    fibonacci_matrix_power_n = powdi(fibonacci_matrix, n)

    return (fibonacci_matrix_power_n @ f0f1)[0]


In [49]:
fibo(8)

[[13 21]
 [21 34]]


array([21])

In [50]:
powdi(np.array([[0,1],[1,1]]), 8)

array([[13, 21],
       [21, 34]])

In [51]:
assert fibo(8) == 21
assert fibo(10) == 55
assert fibo(0) == 0
assert fibo(1) == 1
assert not fibo(5) == 10

[[13 21]
 [21 34]]
[[34 55]
 [55 89]]
[[1. 0.]
 [0. 1.]]
[[0 1]
 [1 1]]
[[3 5]
 [5 8]]


### Explications

#### Matrix-based `powdi`

The exponent law that we used for the scalar version of `powdi` equally applies to matrices.
That is, it holds that $A^{2k} = (A^k)^2 = A^k * A^k$.
Because of this, the matrix-based implementation of `powdi` works the same way the scalar version does.

Note that we now use the matrix multiplication operator (`@`) instead of the scalar multiplication operator (`*`).

#### Matrix-based fibonacci sequence

Instead of considering individual members of the Fibonacci sequence, we consider overlapping pairs of adjacent sequence members.
We obtain the pairs by moving a sliding window of length 2 over the sequence. 
The first pair would therefore be $\left[\begin{array}{c}
f_0 \\
f_1
\end{array}\right] = \left[\begin{array}{c}
0 \\
1
\end{array}\right]$, the second one $\left[\begin{array}{c}
f_1 \\
f_2
\end{array}\right] = \left[\begin{array}{c}
1 \\
2
\end{array}\right]$, the third one $\left[\begin{array}{c}
f_2 \\
f_3
\end{array}\right] = \left[\begin{array}{c}
2 \\
3
\end{array}\right]$ and so on and so forth.

As shown in exercise 3.1, there is a matrix $A$ such that $A * \left[\begin{array}{c}
f_n \\
f_{n+1}
\end{array}\right] = \left[\begin{array}{c}
f_{n+1} \\
f_{n+2}
\end{array}\right]$.
In simple terms, there is a matrix $A$ that transforms the current pair into the next Fibonacci pair.
This matrix is called the Fibonacci matrix.

Note that we can perform the matrix multiplication again to obtain the element following the next element.
More generally, if we start from the base case $x_0 = \left[\begin{array}{c}
0 \\
1
\end{array}\right]$, performing the matrix multiplication $n$ times yields $x_n$.
That is, $x_n = A^n * x_0$.
The first component of $x_n$ then is the $n$ th member of the Fibonacci sequence.

This is precisely what `fibo` does: First, we construct the base case $x_0$. Then, we construct the Fibonacci matrix $A$ and its $n$ th power.
We then calculate $x_n$, and access its first element since it contains the $n$ th member of the Fibonacci sequence.


### Exercice 3.1

$(1)$ Montrez qu'il existe une matrice $A$ reliant $\left[\begin{array}{c}
f_n \\
f_{n+1}
\end{array}\right]$ à $\left[\begin{array}{c}
f_{n+1} \\
f_{n+2}
\end{array}\right]$ pour tout $n\in \mathbb{N}$.

We search a $2 \times 2$ matrix $A = \begin{bmatrix}
a_{11} & a_{12}\\
a_{21} & a_{22}
\end{bmatrix}$, such that $A * \left[\begin{array}{c}
f_n \\
f_{n+1}
\end{array}\right] = \left[\begin{array}{c}
f_{n+1} \\
f_{n+2}
\end{array}\right]$. If we consider this line-by-line, we obtain:

1. $a_{11} * f_n + a_{12} * f_{n+1}$ and
1. $a_{21} * f_n + a_{22} * f_{n+2}$

This trivially holds for the matrix $A = \begin{bmatrix}
0 & 1\\
1 & 1
\end{bmatrix}$, which is exactly the Fibonacci matrix that we used in the previous exercise.

$(2)$ Trouvez alors une expression de $\left[\begin{array}{c}
f_n \\
f_{n+1}
\end{array}\right]$ selon $A$ et  $\left[\begin{array}{c}
f_0 \\
f_{1}
\end{array}\right]$ .

It holds that $x_n = A^n * x_0$, with $A$ being the Fibonacci matrix and $x_0$ representing the base case, i.e., $x_0 = \left[\begin{array}{c}
0 \\
1
\end{array}\right]$.
This has been previously shown in this exercise.

### Exercice 3.2 - (<font color='#db60cf'>Bonus</font>) Une formule analytique pour $f_n$
Que peut-on dire de $A$ ? Déterminez ses valeurs propres et ses sous-espaces propres associés.

For an eigenvector $x$, the following must hold:

$Ax = \lambda x$

$Ax - \lambda x = 0$

$(A - \lambda I) x = 0$

If this equation holds for all $x$, this means that the matrix $(A - \lambda x)$ transforms any vector to the zero vector.
This implies that the matrix's determinant must be zero.

$det(A - \lambda I) = 0$

$det(\begin{bmatrix}
-\lambda & -1\\
-1 & 1 - \lambda
\end{bmatrix}) = 0$

$-\lambda * (1 - \lambda) - (-1 * (-1)) = 0$

$\lambda^2 - \lambda - 1 = 0$

Solving for $\lambda$ yields $\lambda_1 = \frac{1 + \sqrt{5}}{2}$ and $\lambda_2 = \frac{1 - \sqrt{5}}{2}$


En utilisant $(2)$, en déduire une forme analytique de $f_n$.

<< A REMPLIR PAR L'ETUDIANT >>

## Exercice 4
Implémentez et testez les 3 versions de l'algorithme calculant la sous-suite de somme maximale, c'est-à-dire:
* 3 boucles imbriquées
* 2 boucles imbriquées
* une seule boucle (Kadane)

In [42]:
import typing

def maxSub3(sequence: typing.Sequence[int]) -> int:
    maxSum = 0
    
    for lowerBoundInclusive in range(len(sequence)):
        for upperBoundInclusive in range(lowerBoundInclusive, len(sequence)):
            currentSum = 0

            for intervalIdx in range(lowerBoundInclusive, upperBoundInclusive + 1):
                currentSum += sequence[intervalIdx]

            if currentSum > maxSum:
                maxSum = currentSum

    return maxSum

def maxSub2(sequence: list[int]) -> int:
    maxSum = 0
    
    for lowerBound in range(len(sequence)):
        currentSum = 0

        for upperBound in range(lowerBound, len(sequence)):
            currentSum += sequence[upperBound]

            if currentSum > maxSum:
                maxSum = currentSum

    return maxSum

def maxSub1(sequence: typing.Sequence[int]) -> int:
    maxSum = 0
    currentSum = 0

    for it in sequence:
        currentSum += it

        if currentSum > maxSum:
            maxSum = currentSum
        if currentSum < 0:
            currentSum = 0

    return maxSum

In [43]:
assert maxSub3([4,3,-10,2]) == 7
assert maxSub3([4,3,-10,2,8]) == 10
assert maxSub3([4,-10, 5, -10]) == 5
assert not maxSub3([4,3,-10,2,8]) == -10

assert maxSub2([4,3,-10,2]) == 7
assert maxSub2([4,3,-10,2,8]) == 10
assert maxSub2([4,-10, 5, -10]) == 5
assert not maxSub2([4,3,-10,2,8]) == -10

assert maxSub1([4,3,-10,2]) == 7
assert maxSub1([4,3,-10,2,8]) == 10
assert maxSub1([4,-10, 5, -10]) == 5
assert not maxSub1([4,3,-10,2,8]) == -10

### Explications

Otherwise, it contributes positively to the overall sum.

Whe assume that empty subsequences are permissible.