# Série 1
Ce document contient les différents exercices à réaliser. Veuillez compléter et rendre ces exercices pour la semaine prochaine.

Pour chaque exercice:
* implémentez ce qui est demandé
* commentez votre code
* expliquez **en français** ce que vous avez codé dans la cellule correspondante

Dans vos explications à chacun des exercices, indiquez un pourcentage subjectif d'investissement de chaque membre du groupe. **Des interrogations aléatoires en classe pourront être réalisées pour vérifier votre contribution/compréhension.**

## Exercice 1
Le PGCD (plus grand commun diviseur) est le plus grand nombre entier qui divise simultanément deux autres nombres entiers.

Implémentez l'algorithme d'Euclide permettant de calculer le PGCD de deux nombres entiers. Vous trouverez plus d'informations concernant l'algorithme d'Euclide en cliquant sur ce [lien](https://en.wikipedia.org/wiki/Greatest_common_divisor#Euclid's_algorithm).

In [7]:
def gcd(a: int, b: int):
    while b != 0:
        a, b = b, a % b

    return a


In [8]:
assert gcd(9,6) == 3
assert gcd(6, 9) == 3
assert gcd(24,32) == 8
assert gcd(18,18) == 18
assert not gcd(10,15) == 10
assert not gcd(12,9) == 4
assert not gcd(14,14) == 34

### Explications

<< A REMPLIR PAR L'ETUDIANT >>

## Exercice 2
Implémentez une manière de calculer $x^n$ en utilisant la méthode de dichotomie.

In [13]:
def powdi(x: int, n: int) -> int:
    if n == 0:
        return 1
    if n == 1:
        return x
    if n % 2 == 0:
        return powdi(x, n//2) * powdi(x, n//2)
        
    return x * powdi(x, n//2) * powdi(x, n//2)

In [14]:
assert powdi(2,3) == 8
assert powdi(4,2) == 16
assert powdi(2,2) == 4
assert powdi(4,0) == 1
assert powdi(2,1) == 2
assert not powdi(5,2) == 10
assert not powdi(3,7) == 10
assert not powdi(3,3) == 10

### Explications

This method for calculating the $n$ th power of $x$ is of sublinear complexity.
In contrast to the naive approach which consists in multiplying $x$ $n$-times with itself, this method leverages exponent laws.
Specifically, it makes use of the fact that $x^{2k} = (x^k)^2 = x^k * x^k$.

Now some words on the implementation: the first two if-statements deal with base cases, namely $x^0 = 1$ and $x^1 = x$.
Once we have determined that we're not in one of the base cases, we apply the above scheme.

Note that we don't use the regular division operator `/` but the floor division operator `//` ([docs](https://docs.python.org/3/reference/expressions.html#binary-arithmetic-operations)).
The result of a floor division is that of a regular division with the `floor` function applied to its result.
In other words, we always round down, never up.
This is not a problem when dealing with even exponents.
We need to consider this when dealing with odd exponents, however, as we would otherwise miss one multiplication with `x`.
This is what the last if statement checks for, and explains why we additionally multiply with `x` when dealing with odd numbers.

Note that this scheme only works this way if we're dealing with integer exponents.
This requirement is reflected in the function's signature.

## Exercice 3
La suite de Fibonacci est une suite de nombres entiers dans laquelle chaque nombre $f_{n+2}$ correspond à la somme des deux nombres qui le précèdent, $f_{n+1}+f_{n}$.

Implémentez l'algorithme de Fibonacci en utilisant la multiplication matricielle.

In [48]:
import numpy as np
import numpy.typing as np_typing

type TMatrix = np_typing.NDArray[np.int32] | np_typing.NDArray[np.float64]


def powdi(x: TMatrix, n: int) -> TMatrix:
    if n == 0:
        return np.identity(2)
    if n == 1:
        return x
    if n % 2 == 0:
        return powdi(x, n // 2) @ powdi(x, n // 2)

    return x @ powdi(x, n // 2) @ powdi(x, n // 2)


def fibo(n: int):
    f0f1 = np.array([[0], [1]])

    fibonacci_matrix = np.array([[0, 1], [1, 1]])
    fibonacci_matrix_power_n = powdi(fibonacci_matrix, n)

    return (fibonacci_matrix_power_n @ f0f1)[0]


In [49]:
fibo(8)

[[13 21]
 [21 34]]


array([21])

In [50]:
powdi(np.array([[0,1],[1,1]]), 8)

array([[13, 21],
       [21, 34]])

In [51]:
assert fibo(8) == 21
assert fibo(10) == 55
assert fibo(0) == 0
assert fibo(1) == 1
assert not fibo(5) == 10

[[13 21]
 [21 34]]
[[34 55]
 [55 89]]
[[1. 0.]
 [0. 1.]]
[[0 1]
 [1 1]]
[[3 5]
 [5 8]]


### Explications

#### Matrix-based `powdi`

The exponent law that we used for the scalar version of `powdi` equally applies to matrices.
That is, it holds that $A^{2k} = (A^k)^2 = A^k * A^k$.
Because of this, the matrix-based implementation of `powdi` works the same way the scalar version does.

Note that we now use the matrix multiplication operator (`@`) instead of the scalar multiplication operator (`*`).

#### Matrix-based fibonacci sequence

Instead of considering individual members of the Fibonacci sequence, we consider overlapping pairs of adjacent sequence members.
We obtain the pairs by moving a sliding window of length 2 over the sequence. 
The first pair would therefore be $\left[\begin{array}{c}
f_0 \\
f_1
\end{array}\right] = \left[\begin{array}{c}
0 \\
1
\end{array}\right]$, the second one $\left[\begin{array}{c}
f_1 \\
f_2
\end{array}\right] = \left[\begin{array}{c}
1 \\
2
\end{array}\right]$, the third one $\left[\begin{array}{c}
f_2 \\
f_3
\end{array}\right] = \left[\begin{array}{c}
2 \\
3
\end{array}\right]$ and so on and so forth.

As shown in exercise 3.1, there is a matrix $A$ such that $A * \left[\begin{array}{c}
f_n \\
f_{n+1}
\end{array}\right] = \left[\begin{array}{c}
f_{n+1} \\
f_{n+2}
\end{array}\right]$.
In simple terms, there is a matrix $A$ that transforms the current pair into the next Fibonacci pair.
This matrix is called the Fibonacci matrix.

Note that we can perform the matrix multiplication again to obtain the element following the next element.
More generally, if we start from the base case $x_0 = \left[\begin{array}{c}
0 \\
1
\end{array}\right]$, performing the matrix multiplication $n$ times yields $x_n$.
That is, $x_n = A^n * x_0$.
The first component of $x_n$ then is the $n$ th member of the Fibonacci sequence.

This is precisely what `fibo` does: First, we construct the base case $x_0$. Then, we construct the Fibonacci matrix $A$ and its $n$ th power.
We then calculate $x_n$, and access its first element since it contains the $n$ th member of the Fibonacci sequence.


### Exercice 3.1

$(1)$ Montrez qu'il existe une matrice $A$ reliant $\left[\begin{array}{c}
f_n \\
f_{n+1}
\end{array}\right]$ à $\left[\begin{array}{c}
f_{n+1} \\
f_{n+2}
\end{array}\right]$ pour tout $n\in \mathbb{N}$.

We search a $2 \times 2$ matrix $A = \begin{bmatrix}
a_{11} & a_{12}\\
a_{21} & a_{22}
\end{bmatrix}$, such that $A * \left[\begin{array}{c}
f_n \\
f_{n+1}
\end{array}\right] = \left[\begin{array}{c}
f_{n+1} \\
f_{n+2}
\end{array}\right]$. If we consider this line-by-line, we obtain:

1. $a_{11} * f_n + a_{12} * f_{n+1}$ and
1. $a_{21} * f_n + a_{22} * f_{n+2}$

This trivially holds for the matrix $A = \begin{bmatrix}
0 & 1\\
1 & 1
\end{bmatrix}$, which is exactly the Fibonacci matrix that we used in the previous exercise.

$(2)$ Trouvez alors une expression de $\left[\begin{array}{c}
f_n \\
f_{n+1}
\end{array}\right]$ selon $A$ et  $\left[\begin{array}{c}
f_0 \\
f_{1}
\end{array}\right]$ .

It holds that $x_n = A^n * x_0$, with $A$ being the Fibonacci matrix and $x_0$ representing the base case, i.e., $x_0 = \left[\begin{array}{c}
0 \\
1
\end{array}\right]$.
This has been previously shown in this exercise.

### Exercice 3.2 - (<font color='#db60cf'>Bonus</font>) Une formule analytique pour $f_n$
Que peut-on dire de $A$ ? Déterminez ses valeurs propres et ses sous-espaces propres associés.

For an eigenvector $x$, the following must hold:

$Ax = \lambda x$

$Ax - \lambda x = 0$

$(A - \lambda I) x = 0$

If this equation holds for all $x$, this means that the matrix $(A - \lambda x)$ transforms any vector to the zero vector.
This implies that the matrix's determinant must be zero.

$det(A - \lambda I) = 0$

$det(\begin{bmatrix}
-\lambda & -1\\
-1 & 1 - \lambda
\end{bmatrix}) = 0$

$-\lambda * (1 - \lambda) - (-1 * (-1)) = 0$

$\lambda^2 - \lambda - 1 = 0$

Solving for $\lambda$ yields $\lambda_1 = \frac{1 + \sqrt{5}}{2}$ and $\lambda_2 = \frac{1 - \sqrt{5}}{2}$


En utilisant $(2)$, en déduire une forme analytique de $f_n$.

<< A REMPLIR PAR L'ETUDIANT >>

## Exercice 4
Implémentez et testez les 3 versions de l'algorithme calculant la sous-suite de somme maximale, c'est-à-dire:
* 3 boucles imbriquées
* 2 boucles imbriquées
* une seule boucle (Kadane)

In [42]:
import typing

def maxSub3(sequence: typing.Sequence[int]) -> int:
    maxSum = 0
    
    for lowerBoundInclusive in range(len(sequence)):
        for upperBoundInclusive in range(lowerBoundInclusive, len(sequence)):
            currentSum = 0

            for intervalIdx in range(lowerBoundInclusive, upperBoundInclusive + 1):
                currentSum += sequence[intervalIdx]

            if currentSum > maxSum:
                maxSum = currentSum

    return maxSum

def maxSub2(sequence: list[int]) -> int:
    maxSum = 0
    
    for lowerBound in range(len(sequence)):
        currentSum = 0

        for upperBound in range(lowerBound, len(sequence)):
            currentSum += sequence[upperBound]

            if currentSum > maxSum:
                maxSum = currentSum

    return maxSum

def maxSub1(sequence: typing.Sequence[int]) -> int:
    maxSum = 0
    currentSum = 0

    for it in sequence:
        currentSum += it

        if currentSum > maxSum:
            maxSum = currentSum
        if currentSum < 0:
            currentSum = 0

    return maxSum

In [43]:
assert maxSub3([4,3,-10,2]) == 7
assert maxSub3([4,3,-10,2,8]) == 10
assert maxSub3([4,-10, 5, -10]) == 5
assert not maxSub3([4,3,-10,2,8]) == -10

assert maxSub2([4,3,-10,2]) == 7
assert maxSub2([4,3,-10,2,8]) == 10
assert maxSub2([4,-10, 5, -10]) == 5
assert not maxSub2([4,3,-10,2,8]) == -10

assert maxSub1([4,3,-10,2]) == 7
assert maxSub1([4,3,-10,2,8]) == 10
assert maxSub1([4,-10, 5, -10]) == 5
assert not maxSub1([4,3,-10,2,8]) == -10

### Explications

Otherwise, it contributes positively to the overall sum.

Whe assume that empty subsequences are permissible.